baseURL = "https://jcspencer.github.io"
languageCode = "en-us"
title = "James Spencer"
theme = "anubis"
paginate = 3

#disqusShortname = ""
googleAnalytics = ""

[author]
name = "James Spencer"

[params]
author = "James Spencer"
description = "infosec ramblings"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "light"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
mathjax = false
toc = true
tocWordCount = 500

email = "hello@jcspencer.net"
avatar = "/images/me.png"

# Graphcomment support
#graphcommentId = ""

# utteranc.es support
#utterancesRepo = ""  # mandatory
#utterancesTheme = "" # optional
#utterancesIssue = "" # optional
#utterancesLabel = "" # optional

# Giscus support
#GiscusRepo = ""  # mandatory
#GiscusRepoId = ""  # mandatory
#GiscusCategory = "Announcements" # mandatory
#GiscusCategoryId = ""  # mandatory
#GiscusLazyLoad = false  # optional


[[params.social]]
id = "github"
url = "https://github.com/jcspencer"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 2

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true